# subscribed a already existing library
# you can as well combine this with create a local library,
# then in the same playbook subcribe it.
# keeping different playbook will allow selection of library of choice
---
- name: Subscribed to a existing library
  hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yaml
  tasks:
    - name: Collect facts
      ansible.builtin.set_fact:
        connection_args:
          vcenter_hostname: "{{ vc_name }}"ech
          vcenter_username: "{{ vc_usr_name }}"
          vcenter_password: "{{ vc_passwd }}"
          vcenter_validate_certs: "no"

    - name: Get datastore moid
      ansible.builtin.debug:
        msg: >-
          {{ lookup('vmware.vmware_rest.datastore_moid',
          '/' + dc_name + '/datastore/' + datastore_name,
          **connection_args) }}
    - name: Subscribed a content library
      vmware.vmware_rest.content_subscribedlibrary:
        vcenter_hostname: "{{ vc_name }}"
        vcenter_username: "{{ vc_usr_name }}"
        vcenter_password: "{{ vc_passwd }}"
        vcenter_validate_certs: "{{ vc_vali_certs }}"
        name: "{{ cl_name }}"
        description: "common library for all"
        subscription_info:
          subscription_url: "{{ sub_url }}"
          authentication_method: NONE
          automatic_sync_enabled: false
          on_demand: true
        storage_backings:
          - datastore_id: >-
              {{ lookup('vmware.vmware_rest.datastore_moid',
              '/' + dc_name + '/datastore/' +
              datastore_name, **connection_args) }}
            type: DATASTORE
        state: present
